import { motion } from 'framer-motion'
import { ArrowRight, Star, Lock, Zap } from 'lucide-react'

export const TemplateCard = ({ template, onClick, variant = 'default', index = 0, showVisibilityBadge = false }) => {
  const isPromptIQ = template.visibility === 'promptiq'
  const creditLabel = template.credit_cost_per_image ? `${template.credit_cost_per_image} cr/photo` : `${template.credit_cost ?? 2} credits`
  if (variant === 'compact') return <motion.button initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }} whileTap={{ scale: 0.97 }} onClick={onClick} className="flex w-full items-center gap-4 rounded-2xl p-4 text-left" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)' }}><div className="relative flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl" style={{ background: template.thumbnail_url ? undefined : 'linear-gradient(135deg, rgba(249,115,22,0.2), rgba(234,88,12,0.1))' }}>{template.thumbnail_url ? <img src={template.thumbnail_url} alt={template.name} className="h-full w-full object-cover" /> : <Zap size={24} style={{ color: 'var(--brand)' }} />}</div><div className="min-w-0 flex-1"><div className="mb-0.5 flex items-center gap-2"><h3 className="truncate text-sm font-bold" style={{ fontFamily: 'Syne, sans-serif' }}>{template.name}</h3>{showVisibilityBadge && <span className="shrink-0 rounded-full px-1.5 py-0.5 text-xs font-semibold" style={{ background: isPromptIQ ? 'rgba(249,115,22,0.12)' : 'rgba(16,185,129,0.12)', color: isPromptIQ ? 'var(--brand)' : '#10b981' }}>{isPromptIQ ? 'PromptIQ' : 'Public'}</span>}</div><p className="truncate text-xs" style={{ color: 'var(--text-muted)' }}>{template.description}</p><p className="mt-1 text-xs font-semibold" style={{ color: 'var(--brand)' }}>{isPromptIQ ? '⚡ Free for staff' : `⚡ ${creditLabel}`}</p></div><ArrowRight size={16} style={{ color: 'var(--text-muted)' }} /></motion.button>
  return <motion.button initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.06 }} whileTap={{ scale: 0.98 }} onClick={onClick} className="relative w-full overflow-hidden rounded-3xl text-left" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)', boxShadow: 'var(--shadow-md)' }}><div className="relative flex h-36 w-full items-center justify-center" style={{ background: template.thumbnail_url ? undefined : 'linear-gradient(135deg, rgba(249,115,22,0.15), rgba(234,88,12,0.08))' }}>{template.thumbnail_url ? <img src={template.thumbnail_url} alt={template.name} className="h-full w-full object-cover" /> : <Zap size={40} style={{ color: 'var(--brand)', opacity: 0.45 }} />}{template.is_featured && <span className="absolute left-3 top-3 flex items-center gap-1 rounded-full px-2 py-1 text-xs font-bold text-primary-foreground brand-gradient"><Star size={12} fill="currentColor" />Featured</span>}{isPromptIQ && <span className="absolute right-3 top-3 rounded-full bg-black/60 px-2 py-1 text-xs font-bold text-white"><Lock size={11} className="inline" /> Staff</span>}</div><div className="p-4"><h3 className="font-bold" style={{ fontFamily: 'Syne, sans-serif' }}>{template.name}</h3><p className="mt-1 line-clamp-2 text-sm" style={{ color: 'var(--text-muted)' }}>{template.description}</p><p className="mt-3 text-sm font-bold" style={{ color: 'var(--brand)' }}>{isPromptIQ ? '⚡ PromptIQ' : `⚡ ${creditLabel}`}</p></div></motion.button>
}
