// src/pages/TermsPage.jsx
import { useNavigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

export default function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="min-h-dvh" style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)' }}>
      <header
        className="sticky top-0 z-10 flex items-center gap-3 px-4 h-14"
        style={{ background: 'var(--bg-primary)', borderBottom: '1px solid var(--border-color)' }}
      >
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 rounded-xl" style={{ color: 'var(--text-secondary)' }}>
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-sm font-bold">Terms of Service</h1>
      </header>

      <div className="mx-auto max-w-2xl px-5 py-8 space-y-8" style={{ color: 'var(--text-secondary)', lineHeight: 1.75 }}>

        <div>
          <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Last updated: June 2025</p>
          <p className="mt-3 text-sm">
            These Terms of Service ("Terms") govern your use of Meckury AI and all related services
            provided at meckury.ai ("the Platform"). By accessing or using the Platform, you agree to
            be bound by these Terms in full.
          </p>
        </div>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>1. Age Requirement & Eligibility</h2>
          <p className="text-sm">
            You must be at least 18 years old to use Meckury AI. By creating an account or using the Platform,
            you represent and warrant that you are 18 years of age or older. Accounts found to belong to minors
            will be terminated without notice or refund.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>2. User Responsibility for Generated Content</h2>
          <p className="text-sm">
            Meckury AI provides tools for AI-assisted content generation. You are solely and entirely responsible
            for all content you generate, publish, distribute, or use through the Platform. This includes but
            is not limited to images, videos, audio, scripts, and any derivatives thereof.
          </p>
          <p className="text-sm mt-3">
            Meckury AI, its owners, employees, and affiliates accept no liability whatsoever for any content
            generated by users or for any consequences arising from the use, misuse, distribution, or publication
            of such content. You agree to indemnify and hold Meckury AI harmless from any claims, damages,
            or losses resulting from your generated content or your use of the Platform.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>3. Prohibited Uses</h2>
          <p className="text-sm">You agree not to use the Platform to generate or distribute content that:</p>
          <ul className="mt-2 text-sm space-y-1 list-disc list-inside" style={{ color: 'var(--text-muted)' }}>
            <li>Is illegal under any applicable law or regulation</li>
            <li>Depicts or sexualises minors in any way</li>
            <li>Constitutes non-consensual intimate imagery or deepfakes of real individuals without their consent</li>
            <li>Incites violence, hatred, or discrimination against any person or group</li>
            <li>Infringes on the intellectual property rights of any third party</li>
            <li>Is used for fraud, impersonation, or deceptive purposes</li>
            <li>Violates the terms of any third-party AI provider integrated into the Platform</li>
          </ul>
          <p className="text-sm mt-3">
            Violation of these prohibitions may result in immediate account termination without refund,
            and may be reported to relevant authorities where required by law.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>4. Credits & Payments</h2>
          <p className="text-sm">
            Access to generation features requires credits purchased through the Platform. All credit purchases
            are final and non-refundable unless required by applicable law. Credits have no cash value and
            cannot be transferred between accounts. Meckury AI reserves the right to adjust credit pricing
            and generation costs at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>5. Intellectual Property</h2>
          <p className="text-sm">
            You retain ownership of the original assets you upload to the Platform. For content generated
            using Meckury AI tools, you are granted a non-exclusive licence to use that content for personal
            and commercial purposes, subject to the terms of the underlying AI providers. Meckury AI does not
            claim ownership of your generated content, but reserves the right to use anonymised outputs for
            platform improvement and promotional purposes unless you opt out.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>6. Platform Availability</h2>
          <p className="text-sm">
            We strive to keep Meckury AI available at all times, but we do not guarantee uninterrupted access.
            The Platform may be unavailable due to maintenance, outages, or circumstances beyond our control.
            We are not liable for any losses arising from Platform downtime or generation failures.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>7. Disclaimer of Warranties</h2>
          <p className="text-sm">
            The Platform is provided "as is" and "as available" without warranties of any kind, express or
            implied. We do not warrant the accuracy, completeness, or fitness for any particular purpose of
            any content generated through the Platform.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>8. Limitation of Liability</h2>
          <p className="text-sm">
            To the fullest extent permitted by law, Meckury AI shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of the Platform, including but
            not limited to loss of data, revenue, or reputation.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>9. Termination</h2>
          <p className="text-sm">
            We reserve the right to suspend or terminate your account at any time for violation of these Terms
            or for any conduct we deem harmful to the Platform or its users. You may terminate your account
            at any time by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>10. Governing Law</h2>
          <p className="text-sm">
            These Terms are governed by the laws of the Federal Republic of Nigeria. Any disputes arising
            from your use of the Platform shall be subject to the exclusive jurisdiction of Nigerian courts.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold mb-2" style={{ color: 'var(--text-primary)' }}>11. Contact</h2>
          <p className="text-sm">
            For questions about these Terms, contact us at{' '}
            <a href="mailto:hey@meckury.ai" className="underline" style={{ color: 'var(--brand)' }}>
              hey@meckury.ai
            </a>.
          </p>
        </section>

      </div>
    </div>
  )
}
